var devices = {
    'Kodi':{
        keys:[
            "KEY_LEFT",
            "KEY_UP",
            "KEY_DOWN",
            "KEY_RIGHT",
            "KEY_OK",
            "KEY_HOME",
            "KEY_BACK",
            "KEY_PLAY",
            "KEY_PAUSE",
            "KEY_STOP",
            "KEY_MENU",
            "KEY_OSD",
            "KEY_Home"
        ]
    },
    'Sony_RM-ED035':{
        keys:[
            'KEY_POWER',
            'KEY_VOLUMEUP',
            'KEY_VOLUMEDOWN',
            'KEY_CHANNELUP',
            'KEY_CHANNELDOWN',
            'KEY_LEFT',
            'KEY_RIGHT',
            'KEY_UP',
            'KEY_DOWN',
            'KEY_OK',
            'KEY_MENU',
            'KEY_1',
            'KEY_2',
            'KEY_3',
            'KEY_4',
            'KEY_5',
            'KEY_6',
            'KEY_7',
            'KEY_8',
            'KEY_9',
            'KEY_0',
/*
            'KEY_RED',
            'KEY_GREEN',
            'KEY_YELLOW',
            'KEY_BLUE'
*/
        ]
    },
    'Sony_KDL37EX500':{
        keys:[
            'KEY_POWER',
            'KEY_VOLUMEUP',
            'KEY_VOLUMEDOWN',
            'KEY_LEFT',
            'KEY_RIGHT',
            'KEY_UP',
            'KEY_DOWN',
            'KEY_OK',
            'KEY_MENU'/*,
            'KEY_CHANNELUP',
            'KEY_CHANNELDOWN',
            'KEY_1',
            'KEY_2',
            'KEY_3',
            'KEY_4',
            'KEY_5',
            'KEY_6',
            'KEY_7',
            'KEY_8',
            'KEY_9',
            'KEY_0'*/
        ]
    },
    'JVC_AXR337':{
        keys:[
            'KEY_POWER',
            'KEY_VOLUMEUP',
            'KEY_VOLUMEDOWN',
            'TUNER',
            'TAPE1',
            'TAPE2',
            'PHONO',
            'VIDEO',
            'CD',
            'CDDIRECT'
        ]
    },
    'Arris_VIP2952V2':{
        keys:[
            'KEY_POWER',
            'KEY_MUTE',
            'KEY_VOLUMEUP',
            'KEY_VOLUMEDOWN',
            'KEY_CHANNELUP',
            'KEY_CHANNELDOWN',
            'KEY_LEFT',
            'KEY_RIGHT',
            'KEY_UP',
            'KEY_DOWN',
            'KEY_OK',
            'KEY_BACK',
            'KEY_MENU',
            'KEY_PLAY',
            'KEY_STOP',
            'KEY_FASTFORWARD',
            'KEY_REWIND',
            'KEY_1',
            'KEY_2',
            'KEY_3',
            'KEY_4',
            'KEY_5',
            'KEY_6',
            'KEY_7',
            'KEY_8',
            'KEY_9',
            'KEY_0',
            'KEY_RED',
            'KEY_GREEN',
            'KEY_YELLOW',
            'KEY_BLUE',
            'KEY_TV',
            'KEY_RADIO',
            'KEY_EPG'
        ]
    },
    'SONY_RMT-D175P':{
        keys:[
            'KEY_POWER',
            'KEY_EJECTCD',

            'KEY_LEFT',
            'KEY_RIGHT',
            'KEY_UP',
            'KEY_DOWN',
            'KEY_OK',
            'KEY_BACK',
            'KEY_MENU',

            'KEY_PLAY',
            'KEY_PAUSE',
            'KEY_STOP',
            'KEY_FASTFORWARD',
            'KEY_REWIND',
            'KEY_NEXT',
            'KEY_PREVIOUS',
            'KEY_FORWARD',
            'KEY_BACKWARD',

            'KEY_1',
            'KEY_2',
            'KEY_3',
            'KEY_4',
            'KEY_5',
            'KEY_6',
            'KEY_7',
            'KEY_8',
            'KEY_9',
            'KEY_0'
        ]
    },
    'InterTechno':{
        keys:[
            'a1on',
            'a1off',
            'a2on',
            'a2off',
            'a3on',
            'a3off'
        ]
    }
}
