#!/bin/bash

server=remote.lan

ssh root@$server "chmod 644 /etc/systemd/system/remotepi.service"
ssh root@$server "systemctl enable remotepi.service"
ssh root@$server "systemctl daemon-reload"

rsync -auv src/web/* root@$server:/var/www/
rsync -auv src/python/* root@$server:/usr/lib/python2.7/
rsync -auv src/etc/* root@$server:/etc/

ssh root@$server "service remotepi restart"
ssh root@$server "service lirc restart"
ssh root@$server "service nginx restart"
